server:
  port: 8080

spring:
  application:
    name: card-test-app

  datasource:
    url: jdbc:postgresql://localhost:5432/cards
    name: Pashech
    password: 123987456
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        default_schema: card-test

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  main:
    allow-circular-references: true
